### ISSUE TITLE
1.16.5 Conflict with Extra Storage

### ISSUE THREAD

**Issue by Hiranus** [starforcraft/Cable-Tiers#34] opened 2022-03-29 08:33 UTC
#31 #29 
Both of those issues are caused bu Extra Storage being present. 
And also:
- Requesters don't work and its impossible to change number of items being requested
- Its impossible to put importers & exporters into fluid mode.

If Extra Storage is removed everything seems to work fine.

**Comment by KuroPeach** [comment] 2022-10-22 03:42
Still have this problem in 1.18

**Comment by KuroPeach** [comment] 2022-10-22 06:13
I tried commenting out the I/O bus of ExtraStorage. On the server, CableTiers only the requester and the disk manipulator are disabled, the requester cannot enter numbers, and the disk manipulator cannot change any buttons on the left, But their all work on client side

**Comment by KuroPeach** [comment] 2022-10-22 07:46
![image](https://user-images.githubusercontent.com/19620848/197326960-f0167f80-d49b-4a3b-a08a-cee10e941771.png)
https://github.com/KuroPeach/ExtraStorage/blob/c268d13d51a3f8ca4ad0120cf77f42b82a27ebba/src/main/java/edivad/extrastorage/client/screen/custombutton/AdvancedCrafterModeSideButton.java#L24
https://github.com/KuroPeach/ExtraStorage/blob/c268d13d51a3f8ca4ad0120cf77f42b82a27ebba/src/main/java/edivad/extrastorage/client/screen/dataparameter/AdvancedCrafterTileDataParameterClientListener.java#L15
Guess it's a problem with the way the ExtraStorage redstone control button is written, On the server side, the redstone control buttons of Crafter bin disappear. The biggest conflict between you and his mods is the I/O bus, but the author closed the issues. 
https://github.com/Edivad99/ExtraStorage/issues/57

**Comment by starforcraft** [comment] 2022-10-22 07:54
Hmm thanks for the comments, I think I finally know how to fix it now

**Comment by starforcraft** [comment] 2022-10-25 13:18
[cabletiers-1.16.5-0.546.jar.zip](https://github.com/starforcraft/Cable-Tiers/files/9860581/cabletiers-1.16.5-0.546.jar.zip)
Do you have some free time? Can you try this bug with this file?

**Comment by KuroPeach** [comment] 2022-10-25 13:26
[crash-2022-10-25_21.24.12-fml.txt](https://github.com/starforcraft/Cable-Tiers/files/9860655/crash-2022-10-25_21.24.12-fml.txt)
server and client all can't load

**Comment by KuroPeach** [comment] 2022-10-25 13:28
Oh wait, I didn't notice it was 1.16, I am currently playing 1.18

**Comment by KuroPeach** [comment] 2022-10-25 13:32
Can you build 1.18? I don't have the modpack for 1.16 on my computer and server.

**Comment by KuroPeach** [comment] 2022-10-25 14:22
> [cabletiers-1.16.5-0.546.jar.zip](https://github.com/starforcraft/Cable-Tiers/files/9860581/cabletiers-1.16.5-0.546.jar.zip) Do you have some free time? Can you try this bug with this file?

no problem. 👍 
![image](https://user-images.githubusercontent.com/19620848/197799157-f2e3e76e-a44a-4d80-ae1c-96eaa4531b82.png)

**Comment by starforcraft** [comment] 2022-10-25 15:06
Oh wait I send you the wrong file, here is the right one and it's 1.18.2 
[cabletiers-1.18.2-0.55.jar.zip](https://github.com/starforcraft/Cable-Tiers/files/9861503/cabletiers-1.18.2-0.55.jar.zip)

**Comment by KuroPeach** [comment] 2022-10-26 01:08
> Oh wait I sent you the wrong file, here is the right one and it's 1.18.2 [cabletiers-1.18.2-0.55.jar.zip](https://github.com/starforcraft/Cable-Tiers/files/9861503/cabletiers-1.18.2-0.55.jar.zip)

Server Side Requester and Disk Manipulator Buttons do not work and are not logged, And the ExtraStorage redstone control buttons of Crafter disappear.

**Comment by KuroPeach** [comment] 2022-10-26 01:50
[latest.log](https://github.com/starforcraft/Cable-Tiers/files/9865244/latest.log)
I built a local server separately, this time there is logging, but the game behaves a bit strange, the problem is the same as before, but a new problem occurs, open the requester and the manipulator click the invalid button, the crafter will appear invalid redstone buttons, even two

**Comment by Lvcx01** [comment] 2023-01-04 15:02
I have the same problem with this mod and extra storage in 1.19. If someone know how to fix it....thank you

**Comment by starforcraft** [comment] 2023-01-08 15:36
https://github.com/refinedmods/refinedstorage/issues/3449

**Comment by Eyrievalc** [comment] 2023-05-10 17:48
Are there any updates on this issue? Would be great if my server could use these exporters.

**Comment by Hiattech** [comment] 2023-05-21 06:08
In addition, whitelist/blacklist mode do not work for importers. When setting items in whitelist mode, it pulls everything EXCEPT those in the whitelist. Clicking to change it to blacklist doesn't change it, instead it turns on redstone mode - requires redstone. 
See my filter here: https://imgur.com/a/SfgVcRh
When I put these in the filter, it leaves those in the box and pulls everything else out.

**Comment by AceDrago** [comment] 2023-06-04 18:51
even atm8 1.19.2 version of the mod is having the same issues of not being able to switch redstone and whitelist/blacklist and also the fuzzy mode, plus it is not allowing any changes to stay.

**Comment by starforcraft** [comment] 2023-07-09 13:36
This should be now fixed in 1.20.1. Unfortunately a backport isn't possible.

**Closed by starforcraft** 2023-07-09 13:36 UTC
