### ISSUE TITLE
Crash when opening exporter in 1.18.1

### ISSUE THREAD

**Issue by aAndrew3030** [starforcraft/Cable-Tiers#30] opened 2022-01-25 10:29 UTC
Maybe needs updated to the latest forge 59? 
[crash-2022-01-25_05.25.37-server.txt](https://github.com/starforcraft/Cable-Tiers/files/7932729/crash-2022-01-25_05.25.37-server.txt)

**Comment by starforcraft** [comment] 2022-01-25 14:52
Yeah it needs to be fixed on forge .59, but the problem is you can't run Refined Storage (beta.4) too so even if I would fix that you still can't run the game

**Comment by aAndrew3030** [comment] 2022-01-25 16:53
RS beta 4 seems to be working fine for me on .59, but I guess I am lucky as I see it is crashing for many

**Comment by aAndrew3030** [comment] 2022-01-25 17:41
Scratch my last comment RS just updated to release 1.10

**Comment by starforcraft** [comment] 2022-01-25 18:33
https://www.curseforge.com/minecraft/mc-mods/cable-tiers/files/3623371 This should fix it :)

**Closed by starforcraft** 2022-01-25 18:33 UTC
