### ISSUE TITLE
Import/export bus stopped configuring

### ISSUE THREAD

**Issue by Jly4** [starforcraft/Cable-Tiers#48] opened 2023-01-29 06:25 UTC
Even yesterday the buses were working fine, but today they stopped configuring on my server. I can't remember making any changes to the server settings. And my friend says that everything works for him, everything also works for me, but only in a single game. It's definitely not a matter of rights, since on the server I have op

Minecraft: 1.19.2
Forge: 43.2.3
Java Version: 17.0.1, Eclipse Adoptium
cabletiers-1.19.2-0.5471.jar

**Comment by starforcraft** [comment] 2023-01-29 07:41
Duplicate of https://github.com/starforcraft/Cable-Tiers/issues/34

**Closed by starforcraft** 2023-01-29 07:41 UTC

**Comment by Jly4** [comment] 2023-01-29 09:12
> Duplicate of #34

found the cause of this problem, it is [TexTrue's Rubidium Options](https://www.curseforge.com/minecraft/mc-mods/textrues-rubidium-options). I have had this mod for a long time, but for some reason it just started creating this problem yesterday. After removing it, everything started working fine, but when I added it again, the error reappeared

**Comment by starforcraft** [comment] 2023-01-29 10:14
Huh. That‘s really weird, thanks for the report!
